FROM maven:3.8.3-openjdk-17 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM amazoncorretto:17
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/api-1.0-SNAPSHOT.jar /app
EXPOSE 8082
CMD ["java", "-jar", "api-1.0-SNAPSHOT.jar"]
